// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BrokerPageResponse struct {
	TotalItems  int64     `json:"totalItems"`
	TotalPages  int64     `json:"totalPages"`
	CurrentPage int64     `json:"currentPage"`
	Items       []*Broker `json:"items"`
}

type Character struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Likes int64  `json:"likes"`
}

type CharacterInput struct {
	Name  string `json:"name"`
	Likes int64  `json:"likes"`
}

type GetBrokerItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetTaskItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetTaskResultItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetWorkerItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type StopTaskInput struct {
	InstanceID string `json:"instanceId"`
	BrokerID   string `json:"brokerId"`
	WorkerID   string `json:"workerId"`
}

type StopTaskResponse struct {
	Status int32  `json:"status"`
	Msg    string `json:"msg"`
}

type TaskInput struct {
	InstanceID string `json:"instanceId"`
	BrokerID   string `json:"brokerId"`
	WorkerID   string `json:"workerId"`
	Type       int64  `json:"type"`
	Cron       string `json:"cron"`
	Dna        string `json:"dna"`
	Mutation   string `json:"mutation"`
}

type TaskPageResponse struct {
	TotalItems  int64   `json:"totalItems"`
	TotalPages  int64   `json:"totalPages"`
	CurrentPage int64   `json:"currentPage"`
	Items       []*Task `json:"items"`
}

type TaskResponse struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type TaskResultPageResponse struct {
	TotalItems  int64         `json:"totalItems"`
	TotalPages  int64         `json:"totalPages"`
	CurrentPage int64         `json:"currentPage"`
	Items       []*TaskResult `json:"items"`
}

type WorkerPageResponse struct {
	TotalItems  int64     `json:"totalItems"`
	TotalPages  int64     `json:"totalPages"`
	CurrentPage int64     `json:"currentPage"`
	Items       []*Worker `json:"items"`
}
