// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BrokerPageResponse struct {
	Total    int64     `json:"total"`
	PageSize int64     `json:"pageSize"`
	Current  int64     `json:"current"`
	Items    []*Broker `json:"items"`
}

type GetBrokerItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetLatestTaskResultResponse struct {
	TaskResult *TaskResult `json:"taskResult"`
}

type GetTaskItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetTaskResultItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type GetWorkerItemsInput struct {
	Index int64 `json:"index"`
	Size  int64 `json:"size"`
}

type OneKeyAnalyseResponse struct {
	BrokerID string           `json:"brokerId"`
	WorkerID string           `json:"workerId"`
	Key      string           `json:"key"`
	Result   []*OneKeyAnalyse `json:"result"`
}

type StdResponse struct {
	Status int64  `json:"status"`
	Msg    string `json:"msg"`
}

type TaskInput struct {
	Name       string `json:"name"`
	InstanceID string `json:"instanceId"`
	BrokerID   string `json:"brokerId"`
	WorkerID   string `json:"workerId"`
	Type       int64  `json:"type"`
	Cron       string `json:"cron"`
	Dna        string `json:"dna"`
	Mutation   string `json:"mutation"`
	Remark     string `json:"remark"`
}

type TaskInstanceInput struct {
	TaskID   string `json:"taskId"`
	BrokerID string `json:"brokerId"`
}

type TaskPageResponse struct {
	Total    int64   `json:"total"`
	PageSize int64   `json:"pageSize"`
	Current  int64   `json:"current"`
	Items    []*Task `json:"items"`
}

type TaskResultPageResponse struct {
	Total    int64         `json:"total"`
	PageSize int64         `json:"pageSize"`
	Current  int64         `json:"current"`
	Items    []*TaskResult `json:"items"`
}

type WorkerPageResponse struct {
	Total    int64     `json:"total"`
	PageSize int64     `json:"pageSize"`
	Current  int64     `json:"current"`
	Items    []*Worker `json:"items"`
}
