// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Likes int    `json:"likes"`
}

type CharacterInput struct {
	Name  string `json:"name"`
	Likes int    `json:"likes"`
}

type Task struct {
	Status int    `json:"status"`
	Msg    string `json:"msg"`
}

type TaskInput struct {
	ID       string `json:"id"`
	BrokerID string `json:"broker_id"`
	WorkerID string `json:"worker_id"`
	Type     string `json:"type"`
	Dna      string `json:"dna"`
	Mutation string `json:"mutation"`
}
