name: Release Binary Package
on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, windows/amd64
        goos: [linux, windows]
        goarch: [amd64]
        project_path: ["broker","worker"]
    steps:
    - name: Set output
      id: vars
      run: |
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=date::$(date '+%Y-%m-%dT%H:%M:%S')"
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        overwrite: TRUE
        github_token: ${{ secrets.GH_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./${{ matrix.project_path }}"
        binary_name: ${{ matrix.project_path }}
        extra_files: LICENSE README.md
        asset_name: ${{ matrix.project_path }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.vars.outputs.tag }}
        ldflags: "-X 'config.Version=${{ steps.vars.outputs.tag }}' -X 'config.CommitHash=${{ steps.vars.outputs.sha_short }}' -X 'config.BuildTimestamp=${{ steps.vars.outputs.date }}'"
